name: Test

on: [pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
            
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Java version
        run: java -version

      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Maximiliano"

      # ejecutar shell
      #- name: ls
      #  run: |
      #    chmod +x script.sh
      #      ./script.sh