name: Hola mundo

# trigger the workflow on push events
#on: [push, pull_request]

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main    

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

      - name: touch file
        run: touch file.txt

      - name: Set text
        run: echo "Hola mundo" >> file.txt

      - name: Read file
        run: cat file.txt


  other:
    runs-on: ubuntu-latest
    # esta job depende de la job "hola" (Al finalizar "hola" se ejecuta "other")
    needs: [hola] 

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: LS
        run: ls -al

